import type { Metadata } from "next"
import "../stylesheets/main.scss"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="body-center">{children}</body>
    </html>
  )
}
